/**
 * Admin-side label maps.
 * Usage:  import { AL } from "../../utils/adminLabels";
 *         const L = AL[lang] ?? AL.en;
 *         <h1>{L.dashboard}</h1>
 *
 * Rules:
 *  - English only in AL.en, Chinese only in AL.zh.
 *  - No bilingual strings in either object.
 *  - Keep keys stable; add new keys at the bottom of each section.
 */

const en = {
  // ── Sidebar ─────────────────────────────────────────────────────────────
  platformMenu:       "Platform Menu",
  trialMode:          "Trial Mode",
  groupAdmin:         "ADMIN STUDIO",
  groupRental:        "RENTAL STUDIO",
  groupSale:          "HOME SALE STUDIO",
  groupResources:     "RESOURCES",
  groupSystem:        "SYSTEM",
  dashboard:          "Dashboard",
  rentalDashboard:    "Rental Dashboard",
  newRentalListing:   "New Rental Listing",
  rentalListings:     "Rental Listings",
  rentalLeads:        "Rental Leads",
  trialRequests:      "Trial Requests",
  homeSaleDashboard:  "Home Sale Dashboard",
  newSaleListing:     "New Sale Listing",
  saleListings:       "Sale Listings",
  buyerInquiries:     "Buyer Inquiries",
  photoTips:          "Photo Tips",
  faq:                "FAQ",
  settings:           "Settings",
  exitTrial:          "Exit Trial",
  lockAdmin:          "Lock Admin",

  // ── Dashboard ────────────────────────────────────────────────────────────
  adminDashboard:           "Admin Dashboard",
  adminDashboardDesc:       "Manage Rental Studio and Home Sale Studio from one place.",
  rentalStudio:             "Rental Listing Studio",
  rentalStudioDesc:         "Manage rental listings, applications, marketing copy, photos, videos, QR codes, and publish workflow.",
  rentalListingCount:       "Rental Listings",
  published:                "Published",
  openRentalDashboard:      "Open Rental Dashboard",
  homeSaleStudio:           "Home Sale Studio",
  homeSaleStudioDesc:       "Manage sale listings, buyer inquiries, marketing copy, photos, videos, QR codes, open house, and publish workflow.",
  saleListingCount:         "Sale Listings",
  draft:                    "Draft",
  openHomeSaleDashboard:    "Open Home Sale Dashboard",
  rentalDashboardTitle:     "Rental Dashboard",
  rentalDashboardDesc:      "Manage the rental listing marketing workflow.",
  kpiDraft:                 "Draft",
  kpiReview:                "In Review",
  kpiReady:                 "Ready",
  kpiPublished:             "Published",
  noRentalListings:         "No rental listings yet",
  newRentalListingBtn:      "+ New Rental Listing",
  rentalListingsBtn:        "Rental Listings",
  rentalListingStudioLabel: "RENTAL STUDIO",
  homeSaleStudioLabel:      "HOME SALE STUDIO",

  // ── Status badges ────────────────────────────────────────────────────────
  statusDraft:        "Draft",
  statusReview:       "In Review",
  statusReady:        "Ready to Publish",
  statusPublished:    "Published",
  statusActive:       "Active",
  statusSold:         "Sold",
  statusArchived:     "Archived",
  statusAvailable:        "Available",
  statusOpenHouse:        "Open House",
  statusPending:          "Pending",
  statusRented:           "Rented",
  statusApplicationClosed:"Application Closed",
  perMonth:           "/mo",

  // ── Shared actions ───────────────────────────────────────────────────────
  save:               "Save",
  saving:             "Saving…",
  saved:              "Saved",
  cancel:             "Cancel",
  edit:               "Edit",
  delete:             "Delete",
  refresh:            "Refresh",
  loading:            "Loading…",
  back:               "Back",
  next:               "Next",
  open:               "Open",
  close:              "Close",
  copy:               "Copy",
  copied:             "Copied",
  view:               "View",
  publish:            "Publish",
  runAgain:           "Run Again",
  tryAgain:           "Try Again",
  viewPublicPage:     "Public Page",
  editListing:        "Edit Listing",
  openFolder:         "Open Drive Folder",
  openEnhancedFolder: "Open Enhanced Photos Folder",
  openSubfolder:      "Open Folder",

  // ── Rental Listings page ─────────────────────────────────────────────────
  rentalListingsTitle:    "Rental Listings",
  noListings:             "No listings found.",
  colListingId:           "Listing ID",
  colAddress:             "Address",
  colCity:                "City",
  colRent:                "Rent",
  colStatus:              "Status",
  colCreated:             "Created",
  colAction:              "Action",

  // ── New Rental Listing ───────────────────────────────────────────────────
  newRentalListingTitle:  "New Rental Listing",
  ownerInfo:              "Owner Information",
  propertyDetails:        "Property Details",

  // ── Rental Listing Detail ────────────────────────────────────────────────
  finalPackage:           "Final Package",
  propertyInfo:           "Property Information",
  platformOutputs:        "Platform Outputs",
  mediaChecklist:         "Media Checklist",
  generatedContent:       "Generated Content",
  workflowSummary:        "Workflow Summary",
  photoAssets:            "Photo Assets",
  videoOutput:            "Video Output",
  driveVideoOutput:       "Drive Video Output",
  videoScript:            "Video Script",
  voiceover:              "Voiceover",
  photoSource:            "Photo Source",
  videoFormat:            "Video Format",
  publishToPublicPage:    "Publish to Public Page",
  publishing:             "Publishing…",
  musicLabel:             "Music",
  noMusic:                "No music",
  coverPhoto:             "Cover Photo",
  photoReviewStatus:      "Photo Review Status",
  tabFacebook:            "Facebook",
  tabCraigslist:          "Craigslist",
  tabWechat:              "WeChat",
  tabVideoScript:         "Video Script",
  tabOwnerSummary:        "Owner Summary",
  tabEnglishAd:           "English Ad",
  tabChineseSummary:      "Chinese Summary",
  generateContent:        "Generate Content",
  regenerate:             "Regenerate",
  copyText:               "Copy Text",

  // ── Rental Listing Detail — Property Info fields ─────────────────────────
  publicStatus:            "Public Status",
  editListingInfo:         "Edit Listing Info",
  savedToSheet:            "Saved to Sheet",
  openPublicListingPreview:"Open Public Listing Preview",
  fieldOwnerName:               "Owner Name",
  fieldPropertyAddress:         "Property Address",
  fieldCity:                    "City",
  fieldBedrooms:                "Bedrooms",
  fieldBathrooms:               "Bathrooms",
  fieldRent:                    "Rent",
  fieldRentMonthly:             "Rent ($/mo)",
  fieldAvailableDate:           "Available Date",
  fieldLeaseTerm:               "Lease Term",
  fieldUtilities:               "Utilities",
  fieldPetPolicy:               "Pet Policy",
  fieldParking:                 "Parking",
  fieldLaundry:                 "Laundry",
  fieldSmokingPolicy:           "Smoking Policy",
  fieldDefaultLanguage:         "Default Language",
  fieldTargetAudience:          "Target Audience",
  fieldTenantListingStatus:     "Tenant Listing Status",
  fieldTargetPlatforms:         "Target Platforms",
  fieldKeyFeatures:             "Key Features / Headline",
  fieldKeyFeaturesView:         "Key Features",
  fieldOpenHouseSettings:       "Open House Settings",
  fieldOpenHouseDateTime:       "Date / Time",
  fieldOpenHouseViewingInstructions: "Viewing Instructions",
  fieldOpenHouseParkingNotes:   "Parking / Access Notes",
  openHouseDateTimePlaceholder:    "Sunday 2:00 PM - 4:00 PM",
  openHouseViewingPlaceholder:     "Please enter from the side entrance and scan the QR code on arrival.",
  openHouseParkingPlaceholder:     "Street parking only. Please keep the access area clear.",
  openHouseHint:            "Open House content only appears on the tenant-facing page when Tenant Listing Status is set to Open House.",
  editingNotice:            "Editing will update the Google Sheet row for {id}. No new columns or rows will be created.",
  saveToSheet:              "Save to Sheet",
  resetToSheetData:         "Reset to Sheet Data",
  writesDirectlyNotice:     "Writes directly to Google Sheet — no separate sync needed.",

  // ── Dashboard / listing card notices ──────────────────────────────────────
  loadFailedRental:         "Failed to load rental listings",
  loadFailedListings:       "Failed to load listings",
  loadFailedDashboard:      "Failed to load platform dashboard.",
  dashboardDataWarning:     "Dashboard data warning",

  // ── Home Sale pages ───────────────────────────────────────────────────────
  saleListingsTitle:          "Sale Listings",
  newSaleListingBtn:          "+ New Sale Listing",
  editSaleListing:            "Edit Sale Listing",
  newSaleListingTitle:        "New Sale Listing",
  saleFinalPackage:           "Sale Listing Final Package",
  salePropertyInfo:           "Sale Property Information",
  workflowSummaryTitle:       "Workflow Summary",
  photoAssetsTitle:           "Photo Assets",
  coverPhotoSet:              "Cover photo set",
  photosSynced:               "Photos synced from Google Drive",
  videoReady:                 "Video script or AI video ready",
  publishedOpenHouseSold:     "Published / Open House / Sold",
  photoEnhancement:           "AI Deep Photo Enhancement",
  originalPhotos:             "Original Photos",
  virtualStaging:             "Virtual Staging",
  coverImage:                 "Cover Image",
  marketingCopy:              "Marketing Copy",
  videoScriptNav:             "Video Script · Music · Voiceover · AI Video",
  shareKit:                   "Share Kit / QR",
  openHouse:                  "Open House",
  showingAvailability:        "Showing Availability",
  reviewPublish:              "Review & Publish",
  listingInfo:                "Listing Info",
  marketingCopyTitle:         "Marketing Copy",
  addOrUpdateCopy:            "Add or Update Copy",
  shareKitTitle:              "Share Kit",
  saleQrCode:                 "Sale QR Code",
  marketingShareBlocks:       "Marketing Copy Share Blocks",
  openHouseTitle:             "Open House",
  buyerInquiryTitle:          "Buyer Inquiry & Showing",
  showingRequests:            "Showing Requests",
  buyerShowingTitle:          "Buyer Showing Requests",
  sellerNotes:                "Seller Notes",
  reviewPublishTitle:         "Review & Publish",
  publishStatus:              "Publish Status",
  allStepsComplete:           "All steps complete. Change status to Published or Active above.",
  internalStatus:             "Internal Status",
  statusLabel:                "Status",

  // ── Media checklist items ────────────────────────────────────────────────
  checklistPhotos:    "Photo Assets",
  checklistCover:     "Cover Photo",
  checklistVideo:     "Video Script / AI Video",
  checklistPublished: "Published / Open House / Sold",

  // ── Application Review ───────────────────────────────────────────────────
  manualReviewStatus:   "Manual Review Status",
  dateOfBirth:          "Date of Birth",
  employmentStatus:     "Employment Status",
  landlordReference:    "Landlord / Property Mgr Reference",
  totalOccupants:       "Total Occupants",
  jointDob:             "Joint Applicant DOB",
  jointEmployment:      "Joint Employment Status",
  landlordCreditTitle:  "Landlord Reference & Credit",

  // ── Admin Settings ───────────────────────────────────────────────────────
  adminSettingsTitle:   "Admin Settings",
  adminAccessCode:      "Admin Access Code",

  // ── Trial Requests ───────────────────────────────────────────────────────
  trialRequestsTitle:   "Trial Requests",
  adminNotes:           "Admin Notes",
  paymentStatus:        "Payment Status",

  // ── Dashboard v2 — Start Here + My Listings + Next Step ─────────────────
  startNewListing:          "Start a New Listing",
  startNewListingHint:      "Create a listing and follow the step-by-step workflow.",
  newRentalListingCta:      "Rental Listing",
  newSaleListingCta:        "Home Sale Listing",
  myListings:               "My Listings",
  filterAll:                "All",
  filterDraft:              "Draft",
  filterInProgress:         "In Progress",
  filterPublished:          "Published",
  dashNoListings:           "No listings yet",
  dashNoListingsHint:       "Create your first listing to get started.",
  filterNoResults:          "No listings match this filter.",
  nextStepCompleteDetails:  "Complete listing details",
  nextStepUploadPhotos:     "Upload photos",
  nextStepGenerateCopy:     "Generate AI copy",
  nextStepCreateVideo:      "Create video",
  nextStepReviewPublish:    "Review and publish",
  nextStepPublishNow:       "Publish now",
  nextStepMonitorApps:      "Monitor applications",
  nextStepMonitorInquiries: "Monitor inquiries",
  recommendedNextStep:      "Recommended Next Step",
  advancedTools:            "Quick Access",
};

const zh = {
  // ── Sidebar ─────────────────────────────────────────────────────────────
  platformMenu:       "平台菜单",
  trialMode:          "试用模式",
  groupAdmin:         "管理后台",
  groupRental:        "出租房源",
  groupSale:          "出售房源",
  groupResources:     "资源",
  groupSystem:        "系统",
  dashboard:          "总览",
  rentalDashboard:    "出租后台",
  newRentalListing:   "新增出租房源",
  rentalListings:     "出租房源列表",
  rentalLeads:        "租客申请",
  trialRequests:      "试用申请",
  homeSaleDashboard:  "出售后台",
  newSaleListing:     "新增出售房源",
  saleListings:       "出售房源列表",
  buyerInquiries:     "买家咨询",
  photoTips:          "拍照建议",
  faq:                "常见问题",
  settings:           "系统设置",
  exitTrial:          "退出试用",
  lockAdmin:          "锁定",

  // ── Dashboard ────────────────────────────────────────────────────────────
  adminDashboard:           "管理后台",
  adminDashboardDesc:       "统一管理出租房源与出售房源营销工作流。",
  rentalStudio:             "出租房源工作台",
  rentalStudioDesc:         "管理出租房源、租客申请、营销文案、照片、视频、二维码和发布流程。",
  rentalListingCount:       "出租房源",
  published:                "已发布",
  openRentalDashboard:      "打开出租后台",
  homeSaleStudio:           "出售房源工作台",
  homeSaleStudioDesc:       "管理出售房源、买家咨询、营销文案、照片、视频、二维码、开放日和发布流程。",
  saleListingCount:         "出售房源",
  draft:                    "草稿",
  openHomeSaleDashboard:    "打开出售后台",
  rentalDashboardTitle:     "出租后台",
  rentalDashboardDesc:      "管理出租房源营销工作流。",
  kpiDraft:                 "草稿",
  kpiReview:                "审核中",
  kpiReady:                 "待发布",
  kpiPublished:             "已发布",
  noRentalListings:         "暂无出租房源",
  newRentalListingBtn:      "+ 新增出租房源",
  rentalListingsBtn:        "出租房源列表",
  rentalListingStudioLabel: "出租房源",
  homeSaleStudioLabel:      "出售房源",

  // ── Status badges ────────────────────────────────────────────────────────
  statusDraft:        "草稿",
  statusReview:       "审核中",
  statusReady:        "待发布",
  statusPublished:    "已发布",
  statusActive:       "上线中",
  statusSold:         "已售出",
  statusArchived:     "已归档",
  statusAvailable:        "可入住",
  statusOpenHouse:        "开放日",
  statusPending:          "待定",
  statusRented:           "已出租",
  statusApplicationClosed:"申请已关闭",
  perMonth:           "/月",

  // ── Shared actions ───────────────────────────────────────────────────────
  save:               "保存",
  saving:             "保存中…",
  saved:              "已保存",
  cancel:             "取消",
  edit:               "编辑",
  delete:             "删除",
  refresh:            "刷新",
  loading:            "加载中…",
  back:               "返回",
  next:               "下一步",
  open:               "打开",
  close:              "关闭",
  copy:               "复制",
  copied:             "已复制",
  view:               "查看",
  publish:            "发布",
  runAgain:           "重新运行",
  tryAgain:           "重试",
  viewPublicPage:     "公开页面",
  editListing:        "编辑房源",
  openFolder:         "打开 Drive 文件夹",
  openEnhancedFolder: "打开美化照片文件夹",
  openSubfolder:      "打开文件夹",

  // ── Rental Listings page ─────────────────────────────────────────────────
  rentalListingsTitle:    "出租房源列表",
  noListings:             "暂无房源。",
  colListingId:           "房源编号",
  colAddress:             "地址",
  colCity:                "城市",
  colRent:                "租金",
  colStatus:              "状态",
  colCreated:             "创建日期",
  colAction:              "操作",

  // ── New Rental Listing ───────────────────────────────────────────────────
  newRentalListingTitle:  "新增出租房源",
  ownerInfo:              "房东信息",
  propertyDetails:        "房源信息",

  // ── Rental Listing Detail ────────────────────────────────────────────────
  finalPackage:           "最终套件",
  propertyInfo:           "房源信息",
  platformOutputs:        "平台产出",
  mediaChecklist:         "媒体清单",
  generatedContent:       "已生成内容",
  workflowSummary:        "制作状态总览",
  photoAssets:            "房源照片",
  videoOutput:            "视频产出",
  driveVideoOutput:       "视频输出预览",
  videoScript:            "视频脚本",
  voiceover:              "配音",
  photoSource:            "照片来源",
  videoFormat:            "视频格式",
  publishToPublicPage:    "发布到公开页面",
  publishing:             "发布中…",
  musicLabel:             "背景音乐",
  noMusic:                "不加音乐",
  coverPhoto:             "封面照片",
  photoReviewStatus:      "照片审核状态",
  tabFacebook:            "Facebook",
  tabCraigslist:          "Craigslist",
  tabWechat:              "微信",
  tabVideoScript:         "视频脚本",
  tabOwnerSummary:        "房东摘要",
  tabEnglishAd:           "英文广告",
  tabChineseSummary:      "中文版",
  generateContent:        "生成内容",
  regenerate:             "重新生成",
  copyText:               "复制文本",

  // ── Rental Listing Detail — Property Info fields ─────────────────────────
  publicStatus:            "公开状态",
  editListingInfo:         "编辑房源信息",
  savedToSheet:            "已保存到表格",
  openPublicListingPreview:"打开公开预览页面",
  fieldOwnerName:               "房东姓名",
  fieldPropertyAddress:         "房源地址",
  fieldCity:                    "城市",
  fieldBedrooms:                "卧室数量",
  fieldBathrooms:               "卫生间数量",
  fieldRent:                    "租金",
  fieldRentMonthly:             "月租金 ($/月)",
  fieldAvailableDate:           "可入住日期",
  fieldLeaseTerm:               "租约期限",
  fieldUtilities:               "水电费",
  fieldPetPolicy:               "宠物政策",
  fieldParking:                 "停车位",
  fieldLaundry:                 "洗衣设施",
  fieldSmokingPolicy:           "吸烟政策",
  fieldDefaultLanguage:         "默认语言",
  fieldTargetAudience:          "目标租客",
  fieldTenantListingStatus:     "租客可见状态",
  fieldTargetPlatforms:         "目标平台",
  fieldKeyFeatures:             "主要特色 / 标题",
  fieldKeyFeaturesView:         "主要特色",
  fieldOpenHouseSettings:       "开放日设置",
  fieldOpenHouseDateTime:       "日期 / 时间",
  fieldOpenHouseViewingInstructions: "看房须知",
  fieldOpenHouseParkingNotes:   "停车 / 出入须知",
  openHouseDateTimePlaceholder:    "周日 下午2:00 - 4:00",
  openHouseViewingPlaceholder:     "请从侧门进入，到达后请扫描二维码登记。",
  openHouseParkingPlaceholder:     "仅限路边停车，请保持出入通道畅通。",
  openHouseHint:            "仅当「租客可见状态」设为「开放日」时，开放日信息才会显示在租客页面上。",
  editingNotice:            "编辑将更新 Google 表格中 {id} 对应的行，不会新增列或行。",
  saveToSheet:              "保存到表格",
  resetToSheetData:         "重置为表格数据",
  writesDirectlyNotice:     "将直接写入 Google 表格，无需额外同步。",

  // ── Dashboard / listing card notices ──────────────────────────────────────
  loadFailedRental:         "出租房源加载失败",
  loadFailedListings:       "房源加载失败",
  loadFailedDashboard:      "平台看板加载失败。",
  dashboardDataWarning:     "看板数据加载警告",

  // ── Home Sale pages ───────────────────────────────────────────────────────
  saleListingsTitle:          "出售房源列表",
  newSaleListingBtn:          "+ 新增出售房源",
  editSaleListing:            "编辑出售房源",
  newSaleListingTitle:        "新增出售房源",
  saleFinalPackage:           "出售房源详情",
  salePropertyInfo:           "出售房源资料",
  workflowSummaryTitle:       "制作状态总览",
  photoAssetsTitle:           "房源照片",
  coverPhotoSet:              "封面已设定",
  photosSynced:               "照片已同步",
  videoReady:                 "视频脚本已备好",
  publishedOpenHouseSold:     "已发布或出售",
  photoEnhancement:           "AI 深度照片美化",
  originalPhotos:             "原始照片",
  virtualStaging:             "虚拟布置",
  coverImage:                 "封面图",
  marketingCopy:              "营销文案",
  videoScriptNav:             "视频脚本 · 音乐 · 配音 · AI 视频",
  shareKit:                   "分享素材 / 二维码",
  openHouse:                  "开放日",
  showingAvailability:        "看房时间管理",
  reviewPublish:              "审核发布",
  listingInfo:                "房源信息",
  marketingCopyTitle:         "营销文案",
  addOrUpdateCopy:            "新增或更新文案",
  shareKitTitle:              "分享素材",
  saleQrCode:                 "出售房源二维码",
  marketingShareBlocks:       "营销文案分享块",
  openHouseTitle:             "开放日",
  buyerInquiryTitle:          "买家咨询与看房管理",
  showingRequests:            "看房申请",
  buyerShowingTitle:          "买家看房预约管理",
  sellerNotes:                "卖家备注",
  reviewPublishTitle:         "审核与发布",
  publishStatus:              "发布状态",
  allStepsComplete:           "所有步骤已完成，可将状态更改为已发布或上线中。",
  internalStatus:             "内部状态",
  statusLabel:                "状态",

  // ── Media checklist items ────────────────────────────────────────────────
  checklistPhotos:    "房源照片",
  checklistCover:     "封面照片",
  checklistVideo:     "视频脚本已备好",
  checklistPublished: "已发布或出售",

  // ── Application Review ───────────────────────────────────────────────────
  manualReviewStatus:   "人工审核状态",
  dateOfBirth:          "出生日期",
  employmentStatus:     "就业状态",
  landlordReference:    "房东 / 物业管理人参考",
  totalOccupants:       "总人数",
  jointDob:             "联名申请人出生日期",
  jointEmployment:      "联名申请人就业状态",
  landlordCreditTitle:  "房东参考与信用",

  // ── Admin Settings ───────────────────────────────────────────────────────
  adminSettingsTitle:   "管理员设置",
  adminAccessCode:      "管理员访问密码",

  // ── Trial Requests ───────────────────────────────────────────────────────
  trialRequestsTitle:   "试用申请",
  adminNotes:           "管理备注",
  paymentStatus:        "付款状态",

  // ── Dashboard v2 — Start Here + My Listings + Next Step ─────────────────
  startNewListing:          "新建房源",
  startNewListingHint:      "创建房源并按步骤完成发布流程。",
  newRentalListingCta:      "出租房源",
  newSaleListingCta:        "出售房源",
  myListings:               "我的房源",
  filterAll:                "全部",
  filterDraft:              "草稿",
  filterInProgress:         "进行中",
  filterPublished:          "已发布",
  dashNoListings:           "暂无房源",
  dashNoListingsHint:       "创建第一个房源，开始营销工作流。",
  filterNoResults:          "没有符合条件的房源。",
  nextStepCompleteDetails:  "完善房源信息",
  nextStepUploadPhotos:     "上传照片",
  nextStepGenerateCopy:     "生成 AI 文案",
  nextStepCreateVideo:      "制作视频",
  nextStepReviewPublish:    "审核并发布",
  nextStepPublishNow:       "立即发布",
  nextStepMonitorApps:      "查看租客申请",
  nextStepMonitorInquiries: "查看买家咨询",
  recommendedNextStep:      "建议下一步",
  advancedTools:            "快速访问",
};

export const AL = { en, zh };

/**
 * Maps raw status values stored in the sheet (always English) to the
 * localized label for display. Falls back to the raw value if no
 * mapping exists, so unexpected statuses never disappear.
 */
const STATUS_LABEL_KEYS = {
  "Draft":              "statusDraft",
  "In Review":          "statusReview",
  "Ready to Publish":   "statusReady",
  "Published":          "statusPublished",
  "Active":             "statusActive",
  "Sold":               "statusSold",
  "Archived":           "statusArchived",
  "Available":          "statusAvailable",
  "Open House":         "statusOpenHouse",
  "Pending":            "statusPending",
  "Rented":             "statusRented",
  "Application Closed": "statusApplicationClosed",
};

export function getStatusLabel(status, lang) {
  const L = AL[lang] ?? AL.en;
  const key = STATUS_LABEL_KEYS[status];
  return key ? L[key] : (status || "");
}
